##---------------------------------------------------------------------##
# Simulation parameters
uav_platoon:
  n_vehicles: [1, 1, 6]
  initial_pos: [1, 2, 3]
  chase_distance: 5

ugv_platoon:
  n_vehicles: [1, 1, 3]
  initial_pos: [15, 2, 3]
  chase_distance: 5
##---------------------------------------------------------------------##
# Parameter fields
uav_primitives:
  primitives: ['formation', 'formation', 'formation']

ugv_primitives:
  primitives: ['formation', 'formation', 'formation']
##---------------------------------------------------------------------##
# Attributes fields
uav:
  primitive: 'planning'
  n_vehicles: []
  target_pos: [42.88642, -78.87816, 1]
  vehicles_id: []
  vehicles_type: 'uav'
  vehicles: []
  centroid_pos: []
  platoon_id: 0
  initial_formation: True
  selected: False
  execute: True
  casualities: []
##---------------------------------------------------------------------##
ugv:
  primitive: 'planning'
  n_vehicles: []
  target_pos: [42.88642, -78.87816, 1]
  vehicles_id: []
  vehicles_type: 'ugv'
  vehicles: []
  centroid_pos: []
  platoon_id: 0
  initial_formation: True
  selected: False
  execute: True
  casualities: []
##---------------------------------------------------------------------##
